language: python
python: 3.6
cache: pip
env:
  global:
  - secure: d872J1c695iZB9UMLc+avIFY9UpQ0SSiLVMfJNfVLHgCJ8wgeL0D4cG6yfll3GSS7XDpypC6CKraJ3fl2VEQtvfkg0ppb1miws0WJjEaDfhsbDpWKMaWSWHk6Z5V2oRmXrsGcpqgo4wcmPofAQZmWmpbjgpe4MgMg46+l53rBMomM7DAi5fsc4prrSpjMyAfUcJo9PeR2Q2qS6PEGGaMhSxjUmcSS6H6WJ8EfQ3DYodRdfEs/aVgKNZ8Ia520iisnLxfytoNg9qGxIsL4/qs9rm8i0Wvmcu7xCpPnZJQt3IFGcnTpoB/0A4Lv/NkHIJi9RKP485zye+wOMI3OPFqkaiPCIyh3Hqz+vPOzRr737F31pmsz9DGf44gjJ+Q5InInQhsbg/qIf851N5erIKB+ZPPMlXa7ctUDCEFv3fADDz8XtSQVKVetEZ9T6Wj+fxfVV6zS6C0DJhQ2sJqrzyQqdkl1in+ZWZ5MFmkgiOzFTR7kaxPNzswDE2TAKSMr1GCnqcvrhdMinJaaAz/egnViTYQT5n6Qio8oR+70X7kXbViCXtmp5o30iG/bJR1Vdc7nVDeiH2OyuuUcI+RkaneClARrGMBx2LpF1zVNi4b1DIL0gv89bykHFzk7i9+ONgeNNOhw630gf84DU4nXUOdLMi3BpGxV5mzUuBBlIiXKHI=
  - secure: SisCuYo6AW33TW2m95EIoE7DqyfH90MXLLsskraWxfdl/DdTsVImBjs/ZUw8zBeU1PBIHnhbTvYOLn7lneKiG8fS1i8LHssN5fi0cWVM8w0SCwAMuqdCIDEb0n2sP2f+RRwwYPaIDobRZboOyuuen2UJv3KDL6qFeu+mjAKYW/vgM8uZQnrE/KaHBZUJKBhC7Wpqcl8tppWi6itpv48IMWAh2xXmQqT9Sf/Tr36zAS1rQ5f+S+Z9FB0yCNhcGAMYjJjXDrRDdA7xj4aL719h+eR0qjTIf5Zz7BVfQ7u7WZFjWigOBtf8hor39jYVIwS7pEbDAlWPe0BdtdBgFm4nWeLGOwIQp4IcfUWhtLj2cPJAEHCCoXxIoTo5wOXrYGr+Elr8Wd8J3fMr0MiwIfdc9vSWEBTr7CE8EP/4+WeHnhUd1+XKIiUMyCiPkQa1RltYocz7xKfIvBRdJiuotU0aReOB/7yI8NgYkiMA6/pGz1nd6FOsXjFp3Wx3RaAMSWy7Weq88p/ZCLbAcWXBvm4D0Uk0TNzDkqYTkhPJ1UJaHMhohr4mRMCnlk3RRPym5zlmJrI8SPXvo/0W1m/XBM4UCW+T/odsx3x8GTPGfTXSNBQcTiSGHPeR6bDVHVV3rQ9V/XUMxp2ASFcJtRdB1UGjyB+r6+/C0b8RjUfJEszI474=
  - secure: SZKZDCJ9WEXPL/HE4EEoElwFjgv8ZcdTEiz+oz5pXvOxgDHsf9xUC8WDRkW4AObMecQ16POuhUgAwvtMnm931QopwwyREz+D0zl+uovelqV8znBS1+LpUSQoozUo2503p84UJ0kZ6+1KGFS7352NrG2SuNH+c9qPFrBQUSktMPZ+3gRa2c8WP30aNGqYGVJhTezRRmAVxFWZ8l8wyHQ3DQmm/bUAp39uNExcY93Etzyb5GKeA/bad2QNwnv7FEBKQ6iQbX4ky56TKzcbZT4R3oSWeKaKXFMtRV8vZSHC/nID6BKNP0y/+ZGrheLUkvHmsFYXDOkYotKuZxlMqXfyQtj9DqrCola+z5ckAZx5cK2wyRqtFWBsEQdSLntq3fk6cqpGAmaLg+so9H80h7YqpVR5XjFQL4FuWDVA6/rD3j+v5z5MEAi3anImD94bFT6cKqMmlVqX5n0Hgatg12SfVYuB2rOf6T0mZeEub6gypK75YFVct56enSJr35zVuscfISIQy6fLx7ti5LJTVeJGbscWPJ11Oo+Y1QNRfGGfKwZUqiZu7ALTRkRTI9MQtzYK4QSQSuhBLIz5bIvvOShxyMhitlO6KsyupxCSsR7PDFqfMlseZJUbv2ong33Ubm4gY5iJP/by6o07WHAdlK7uv7U+980zedhjlIDC8MXb61k=
  - COMMIT=${TRAVIS_COMMIT::7}
jobs:
  include:
  - stage: production build
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=localmotion/playground-importer
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH | sed 's/\//_/g' ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
true:
  branch: master
notifications:
  slack:
    rooms:
      secure: TPkkZMenxWkOvDhK6KVCMa6TloyzJBici1YWpLU38qpcAFcOs32Okoz9adRAd2Pds0+r1E+hi7hrCsrqKmqRanlphAoR18VnYek5CLu1znHX/8Cy38h2NV7EAcykbYYrUnRKRQE/2/S3bjU7HpMmnVk4DuesvoiEb2EvNlDzYGQG5Mg8NmYHkDAwNp9YpQuHoFx3c7L6aR36DDHy+5dnmFa7eb1/+ma3GYjNBfYUkuVC7GCF/P0kybnEp96lXJbouqHpLo2uM4Tar2vHLlXfmGICkkRQ7j5A5scvz+Y8nE1yNYutRTXulWaeSjYwzRpoYpWkVWYICtx5BWXe5DjvL9AX1MnSA3ydg5tlghU8NPt8duPnFnA19Jmlw62Zks5VKNe2U06L12u1/p77nloBP52Ef3OwMO/nkJx/4VWljJQGjwRvc4EiKzvhX3GrybTSisEZKPZEzxGcMZelxrT/8hSh5Z4PHLDA9sLghOB4mLaKbCHoRlY86j/W/76+mgh3FfJN3VmxgYwacNxFdWaREotpE5lwUdCwqIAAjncEfJEFSa4XQ65Mz3z8eOwWGDvxXnD2INgKGAyKvDmrxPJqHcaRO7gA5fYHnPzKgmYHyV2o46iXMcOH8dQskGCPNYMPjlRkNkw9l58Z62r+T0G1d8hwWyAqduiyHEd6Btlx0YQ=
    on_success: always
    on_failure: always
